#!/usr/bin/env bash

SCRIPT_FOLDER="${HOME}/configs2.0/autoscripts"
SCRIPT_FILE="$SCRIPT_FOLDER/$1"

if [[ -f $SCRIPT_FILE ]]; then
  $EDITOR $SCRIPT_FILE
else
  echo '#!/usr/bin/env bash' > $SCRIPT_FILE
  chmod +x $SCRIPT_FILE
  $EDITOR $SCRIPT_FILE
fi

