#!/usr/bin/env bash


TMP_FILE=$(mktemp)
cat > $TMP_FILE

$EMACS_TTY --eval "(let ((buffer (generate-new-buffer \"*temp*\")))
      (set-window-buffer nil buffer)
      (with-current-buffer buffer
        (insert-file \"$TMP_FILE\")))"

rm $TMP_FILE
